 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/chose_ps", type: :request do
  
  # ChoseP. As you add validations to ChoseP, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ChoseP.create! valid_attributes
      get chose_ps_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      chose_p = ChoseP.create! valid_attributes
      get chose_p_url(chose_p)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_chose_p_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      chose_p = ChoseP.create! valid_attributes
      get edit_chose_p_url(chose_p)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ChoseP" do
        expect {
          post chose_ps_url, params: { chose_p: valid_attributes }
        }.to change(ChoseP, :count).by(1)
      end

      it "redirects to the created chose_p" do
        post chose_ps_url, params: { chose_p: valid_attributes }
        expect(response).to redirect_to(chose_p_url(ChoseP.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ChoseP" do
        expect {
          post chose_ps_url, params: { chose_p: invalid_attributes }
        }.to change(ChoseP, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post chose_ps_url, params: { chose_p: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chose_p" do
        chose_p = ChoseP.create! valid_attributes
        patch chose_p_url(chose_p), params: { chose_p: new_attributes }
        chose_p.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the chose_p" do
        chose_p = ChoseP.create! valid_attributes
        patch chose_p_url(chose_p), params: { chose_p: new_attributes }
        chose_p.reload
        expect(response).to redirect_to(chose_p_url(chose_p))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        chose_p = ChoseP.create! valid_attributes
        patch chose_p_url(chose_p), params: { chose_p: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested chose_p" do
      chose_p = ChoseP.create! valid_attributes
      expect {
        delete chose_p_url(chose_p)
      }.to change(ChoseP, :count).by(-1)
    end

    it "redirects to the chose_ps list" do
      chose_p = ChoseP.create! valid_attributes
      delete chose_p_url(chose_p)
      expect(response).to redirect_to(chose_ps_url)
    end
  end
end
