 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/group_memberships", type: :request do
  
  # GroupMembership. As you add validations to GroupMembership, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GroupMembership.create! valid_attributes
      get group_memberships_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      group_membership = GroupMembership.create! valid_attributes
      get group_membership_url(group_membership)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_group_membership_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      group_membership = GroupMembership.create! valid_attributes
      get edit_group_membership_url(group_membership)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GroupMembership" do
        expect {
          post group_memberships_url, params: { group_membership: valid_attributes }
        }.to change(GroupMembership, :count).by(1)
      end

      it "redirects to the created group_membership" do
        post group_memberships_url, params: { group_membership: valid_attributes }
        expect(response).to redirect_to(group_membership_url(GroupMembership.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GroupMembership" do
        expect {
          post group_memberships_url, params: { group_membership: invalid_attributes }
        }.to change(GroupMembership, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post group_memberships_url, params: { group_membership: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested group_membership" do
        group_membership = GroupMembership.create! valid_attributes
        patch group_membership_url(group_membership), params: { group_membership: new_attributes }
        group_membership.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the group_membership" do
        group_membership = GroupMembership.create! valid_attributes
        patch group_membership_url(group_membership), params: { group_membership: new_attributes }
        group_membership.reload
        expect(response).to redirect_to(group_membership_url(group_membership))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        group_membership = GroupMembership.create! valid_attributes
        patch group_membership_url(group_membership), params: { group_membership: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested group_membership" do
      group_membership = GroupMembership.create! valid_attributes
      expect {
        delete group_membership_url(group_membership)
      }.to change(GroupMembership, :count).by(-1)
    end

    it "redirects to the group_memberships list" do
      group_membership = GroupMembership.create! valid_attributes
      delete group_membership_url(group_membership)
      expect(response).to redirect_to(group_memberships_url)
    end
  end
end
